services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: products-api
    restart: unless-stopped
    network_mode: "host"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ASPNETCORE_URLS: "http://+:8081"
      ConnectionStrings__ProductsDb: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"

  postgres:
    image: postgres:16-alpine
    container_name: products-db
    restart: unless-stopped
    profiles: ["local-db"]
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - products_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d products_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  products_db_data: